### ISSUE TITLE
2.2 Объём шара и площадь сферы

### ISSUE THREAD

**Issue by SBasalaev** [arhyme/MatanZP#7]
Полнейшая неразбериха в выводе площади сферы.
* Где-то _k_, где-то _n_.
* В интегралах отсутствует коэффициент искажения.
* Почему-то площадь вычисляется (_n_–2)-мерная, а не (_n_–1)-мерная.

**Comment by arhyme** [comment]
Я исправил, что увидел. Мог что-то не заметить.

**Comment by SBasalaev** [comment]
Tip💡: Багрепорты можно автоматически закрывать коммитами. Для этого в сообщении коммита можно добавить "closes #7" или "fixes #7". Можно одним коммитом закрыть несколько багов.
Подробнее в [справке Github](https://help.github.com/en/articles/closing-issues-using-keywords).
